### ISSUE TITLE
Upgrade: Make Upload Form input rules cleaner.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#14]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [ ] Turn off spellcheck for text fields.
- [ ] Create array of Rules that can be inserts into text field props as an array of rules.
- [ ] Create rule badges underneath each text field.
- [ ] Create a function that is called whenever an invalid input occurs on a text element, called with the argument of the rule being broken.
	- [ ] Headshake Animation for input when invalid
	- [ ] Within the function, check for broken rule and highlight the rule that is being broken.

**Comment by joseph-bravo** [comment]
Splitting it up into #41 and #42
