### ISSUE TITLE
Feature: User can upload their .sar file to storage bucket and give it some metadata (Title, Short Description, Tags).

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#2]
# also resolves #1 

## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can upload their .sar file to storage bucket and give it some metadata (Title, Short Description, Tags).

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking upload, if all the required text inputs are filled, upload the file to the DB alongside the rendered Symbol Art. Reset the form and preview.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![XS_Post Form](https://user-images.githubusercontent.com/78003700/171043062-b7dc91d1-808f-4d95-97f2-e8851f9fbd38.png)
![MD_Post Form](https://user-images.githubusercontent.com/78003700/171043066-9ba34ac6-71de-4f34-8226-56c36321e1d2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Load up schema exported from https://dbdiagram.io/d/629502e5f040f104c1c416e4

### ⚡ Client

- [x] Configure Tailwind CSS and DaisyUI
- [x] Create Layout component with Header and wrap page view inside of it
- [x] Create upload form page with form values tied to state.
- [x] Create file upload button that accepts a `.sar` file, and parses it into Symbol Art object `parsedSymbolArt` upon file input.
	- [x] Implement error checking for `.sar` parsing if the file isn't a proper `.sar` file
- [x] Create component to handle Symbol Art file preview, which is passed `parsedSymbolArt` as props and returns an `img` element with `src` set to the return of `pixi.js` app view.
- [x] If preview is shown, display other form elements to handle title, description, and tags.
- [x] Make sure tags are lowercase upon entry and submit. 
- [x] Restrict description to 90 characters
- [x] Add placeholders
- [x] Upon submit, check if title and description is filled out.
	- [x] If form is valid, send a fetch request to the local server with `.sar` file, thumbnail render, and other form values.

### ☁️ Server

- [x] Set up an account with Amazon S3 and save secret keys in `.env`
- [x] Update `server/index.js` to listen for form submits on path `/api/upload`
	- [x] Hook up `multer` and `multer-s3` libs to upload `.sar` file and `.png` thumbnail to bucket (`/sar-files` and `/thumbnails` directories)
	- [x] Upon successful uploads, insert into `files` table with appropriate file paths
	- [x] Insert into `posts` with appropriate metadata and link to `files` table with generated `fileId` from previous step
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
