### ISSUE TITLE
Feature: User can create an account.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account to upload Symbol Arts from. They can access the log in/sign up page via the navbar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Auth Form](https://user-images.githubusercontent.com/78003700/171044532-0b535a9d-cb77-4939-841b-307b253a921e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) and `argon2`
- [x] Create new TOKEN_SECRET in `.env`
- [x] Create new POST endpoint `/api/auth/sign-up` that takes json body with keys `username` and `password`, and creates an entry in the `users` table in DB with the password hashed with argon and username.
- [x] Respond with a 201 if query is successful, with body of `userId` and `username`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create page `<AuthPage />` to route `/auth` that has a form entry with text inputs `username` and `password`, with header Sign In or Sign Up depending on route `/auth/sign-in` or `/auth/sign-up`
- [x] Add App state `user` and `setUser()` function that is passed down via Context.
- [x] within `<AuthPage />`, check if `user` isn't null. If it isn't, then display form.
- [x] On submit, check for current action. If it's `sign-in`, then send inputs as JSON body to `fetch(/api/auth/sign-up)`. If response is 201, console log result.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
