### ISSUE TITLE
Feature: User can log into their account

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#25]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in to the accounts that they have created

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Within sign-in form, I can input my username and password and submit to login. If it's correct, then it redirects me to catalog page and the header lets me sign out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Image](https://user-images.githubusercontent.com/78003700/172505476-680c1956-0d8a-471f-b111-c5e4e2401177.png)

![Image](https://user-images.githubusercontent.com/78003700/172505495-c5eaa370-97c6-474c-bafd-8bcf6bab8af3.png)

> ## ~~Note: Modal aligns to top if w>=768~~ it doesn't look as bad as I thought it would lol

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create `POST` endpoint `/api/auth/sign-in` that takes a username and password as JSON body.
- [x] Query DB table `users` where `username`, and if exists, verify hashed password with provided password.
- [x] Upon successful hash, sign JWT with `TOKEN_SECRET` and payload of username and user id, which is then sent as response.
- [x] Upon any failures, respond with `401`
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] in `<AuthPage />`, if `action === 'sign-in'`, send a POST fetch to `/api/auth/sign-in` with username and password as JSON body.
- [x] If response is successful, take JWT response body and put into `LocalStorage` under `userjwt` key.
- [x] Upon App first mount AND after sign-in response success, `setState({user:jwt})` to `userjwt` of LocalStorage

~~Create modal Component `<UserActions />` that displays a signout button that clears the `LocalStorage` and sets user state to null
In AppContext, create state from `<App />` to handle `isUserModalOpen`, and display `<UserActions />` within `<Layout />` if it is true.
In header, check if `appContext.user` exists, and if so, display button to access user actions (temporary text content being "user")~~

> I ended up doing this differently: Created `<DaisyModal />` for reusability for other uses of modals, and added it as a child to Header since that's where navigation to user actions reside.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
