### ISSUE TITLE
Feature: User can view all uploaded .sar files (catalog)

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all uploaded .sar files.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User sees a list of all posts that are sorted in chronological order
User can download the .sar file by clicking the download button.
User can preview the sound by clicking the sound tag.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![XS_ViewPosts](https://user-images.githubusercontent.com/78003700/171043315-ded082e1-53b3-43ae-8712-78ff8b31af82.png)
![MD_View Posts](https://user-images.githubusercontent.com/78003700/171043326-0e646115-f3bd-4330-9e67-65bc5df3bf69.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Address #12 
- [x] Update `schema.sql` to accept "object key" for `.sar` files rather than file path.
- [x] Update `data.sql` to contain placeholder data.

### ☁️ Server

- [x] Create `GET` route for path `/api/catalog`
	- [x] Query DB for all posts (columns: title, username, description, file/preview paths, tags), and send as response

#15 has been held off for later

```postgresql
with "tag_arrays" as (
  select
    "postId",
    array_agg("tagName") as "tags"
  from "taggings"
  group by "postId"
)

select  
  "title", "description", "username",
  "filePath", "thumbnailPath",
  "filePropsName", "filePropsSound", "filePropsLayerCount",
  "postId", "userId", "p"."createdAt"
from "posts" as "p"
join "files" using ("fileId")
join "users" using ("userId")
join "tag_arrays" using ("postId")
order by "p"."createdAt"
limit 20
offset $1
;
```

- [x] Create `GET` route for path `/api/post/:id/download` [[Download from S3]]
	- [x] Query DB for post's associated object key and post's title for `.sar` with the provided `id` param. 
	- [x] Generate download URL using [black magic](https://gist.github.com/joseph-bravo/ea19fa99e010ae83e9355efdd54b86ec) provided object key and title and redirect user to that URL to download
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Install [`react-lazy-loag-image-component`](https://www.npmjs.com/package/react-lazy-load-image-component)
- [x] Address #13 
- [x] Add sound files to `public` directory
- [x] Create Page `<AllPosts />`.
	- [x] Send fetch request to `/api/catalog/:offset` with offset being the current amount of posts displayed at the moment.
- [x] Create Component `<SymbolArtCard />` that renders a small card for a single post.
	- [x] Accepts property `source` that takes a `.sar` post detail object
	- [x] Lazy Load image from `source` preview URL
	- [x] Display title, username, description, and tags.
	- [x] Add button that `source`'s sound given sound ID.
	- [x] Add a download button that calls `/api/post/:id/download` to download file

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
