### ISSUE TITLE
Refactor: Move all route middlewares into their own files

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#31]
# Finish #32 first
- [x] Complete #32

---

> ### It would look better than 501 lines inside `server/index.js`

## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] Create `api` directory containing directories and files for each method/endpoint (i.e. `api/auth/post.sign-up.js` or `api/get.catalog.js`. Fill files with middleware associated to endpoint
- [ ] Create `api/index.js` and import all endpoints and put into single object with property of method, which has a value of properties that are the endpoints 

```
module.exports = {
  post: {
    auth: {
      sign-up: require('./post/auth/sign-up');
    }
  }
}
```

- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.

**Comment by joseph-bravo** [comment]
Approved now. Will work on when I get around to it
