### ISSUE TITLE
Refactor: Move all general middlewares into `middlewares/`

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#32]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] move all middleware `.js` files into directory and fix `require()` statements to match new directory
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
