### ISSUE TITLE
Polish: Don't render errors if still `loading`

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#35]
## Todo

- [ ] Refactor all components that rely on async operations to contain `state.loading` boolean. If rendering calls async operation, default to true
- [ ] Upon starting an async operation, set `state.loading` to `true`. Upon finalization, `setState({loading: false})` it.
- [ ] For all error elements, only render them if `state.loading === false` alongside their usual prerequisites
