### ISSUE TITLE
Feature: User can view a detailed view of their uploaded .sar file by navigating to a route of the upload ID.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a detailed view of their uploaded .sar file by navigating to a route of the upload ID.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking a post in All Uploads view or setting the route to the specified Upload ID, user is shown a detailed post view.
Within this view, user can create a sharable link to the .sar file.
Within this view, user can download the .sar file, which is renamed to the post title in kebab case.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MD_ Single Post](https://user-images.githubusercontent.com/78003700/171043532-4423f950-1572-4fac-b5e9-f8730fc6dc26.png)
![XS_ Single Post](https://user-images.githubusercontent.com/78003700/171043536-4b5163a0-f770-4874-a970-6287894455f0.png)

[[Symbol Art Vault]]

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Refactor API endpoint for downloads to `/api/posts/download?id=x`, where `x` is the ID of the post.
- [x] Create new endpoint for viewing posts `/api/posts/view?id=x`, where `x`  is the ID of the post.
	- [x] Query within `posts` where ID is `req.query.id`, join `files` and `taggings` similar to `/api/catalog`, but with a `where` clause.
- [x] Nvm go back to path params they look nicer
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Address #17 
- [x] Move all HREF URL generation to `/lib/endpoints.js`
- [x] Move `playSound()` from `catalog.jsx` into an `<AppContext.Provider />` HOC
	- [x] Refactor `<SymbolArtCard />` to consume `playSound()`
- [x] Create a page `<SinglePost />` view, style according to wireframe.
	- [x] Share link goes to current route. 
	- [x] Access by route `/posts/id`
	- [x] Update `<SymbolArtCard />` to link to `<SinglePost />` view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
