### ISSUE TITLE
Refactor: Concatenate `posts` and `files` table into single table

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#46]
## ✅ Task List

- [ ] Update schema to the following

![NGS Symbol Vault V1 (3)](https://user-images.githubusercontent.com/78003700/173694203-9ccbd952-313f-447d-9030-2e6c7c5b7ed7.png)

- [ ] Adjust queries to account for change in schema
- [ ] Create new savestate
