### ISSUE TITLE
Feature: User can search for Title, Description, or Tags in All Uploads view.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for Title, Description, or Tags in All Uploads view.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Search bar allows user to full text search for any uploaded file.
Sort by the best matching post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![XS_ViewPosts](https://user-images.githubusercontent.com/78003700/171043788-0f31487c-fbeb-49c9-8ff4-f1d98fcfdd86.png)
![MD_View Posts](https://user-images.githubusercontent.com/78003700/171043790-410a3195-8ecc-4eba-a722-ae5a73bd99c1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create endpoint `/api/posts/search?query=x`, where `x` is the search query to be sent

```sql

with "tag_arrays" as (
  select
    "postId",
    array_to_string(array_agg("tagName"), ' ') as "tags"
  from "taggings"
  group by "postId"
), "posts_with_tags" as (
  select * from "posts"
  join "users" using ("userId")
  join "tag_arrays" using ("postId")
), "weighted_posts" as (
  select
    *, 
    setweight(to_tsvector("title"), 'A') ||
    setweight(to_tsvector("description"), 'B') ||
    setweight(to_tsvector("tags"), 'C') ||
    setweight(to_tsvector("username"), 'D')
      as "weights"
  from "posts_with_tags"
), "search_ranking" as (
  select *, ts_rank("weights", plainto_tsquery('pso2')) as "ranks"
  from "weighted_posts"
)

select "title", "description", "tags", "username", "ranks"
from "search_ranking"
where "ranks" > 0.01
order by "ranks" desc
limit 20
;

```

- [x]  Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `<SearchBar />` that takes an input and runs a function on "search" submit button. Put on homepage
	- [x] If Empty, keep catalog as it is. If emptied, revert back to original catalog.
	- [x] Have the `SearchBar`'s function call a fetch request to `api/posts/search` with `query` Query Param set to value of search. (Default to all columns)
	- [x] Update `CatalogPage` state with resulting fetch.
	- [x] Display message if search couldn't find anything
	- [x] Create toggles for each column to search by

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
