### ISSUE TITLE
Feature: User can view .sar file preview within embeds of the link on other platforms

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view .sar file preview within embeds of the link on other platforms

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When pasting the link in an app such as Twitter or Discord, a preview embed will pop up with the upload title, description, and thumbnail preview.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

N/A

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to use `pug` for template rendering.
- [x] Handle get methods for endpoint `/posts/:id`, and query the DB for that post.
- [x] If post exists, render Open Graph meta tags with corresponding data: [title, type, description, image,  twitter:card](https://css-tricks.com/essential-meta-tags-social-media/)
- [x] Create fallback content for if post doesn't exist
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
