### ISSUE TITLE
Feature: User can upload Symbol Arts from an account

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#7]
- [x] #21

## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can can upload Symbol Arts from their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When logged in, uploading a post will attach their user data to the new post
If a User uploads a Symbol Art without logging in, it is considered an Anonymous post

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

N/A

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Repurpose `userId=1` to "anonymous" dummy account in `"users"`

### ☁️ Server

- [x] Create authorization middleware that checks headers of `req` for `X-Access-Token`.
- [x] Verify the token with `jwt` and the `TOKEN_SECRET` in a `try catch` statement, and attach the payload's user id to `req.userid` if successful. After that, call `next()`
- [x] Sets req.userid to `1` if `X-Access-Token` is not provided
- [x] Throw JWT Error if token is invalid
- [x] Add JWT Error handler to `error-middleware.js`
- [x] Insert `authorizationLooseMiddleware` into `/api/upload` middleware pipeline before generating the UUID.
- [x] Replace placeholder `1` with `req.userid` in `/api/upload` 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Send `AppContext.userToken` as `'X-Access-Token'` Header on upload `fetch` request.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
