### ISSUE TITLE
Feature: User can click on the author in single post view to view all Symbol Arts uploaded from the author.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the author in single post view to view all Symbol Arts uploaded from the author.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the author in any Symbol Art preview card to view all Symbol Arts uploaded from the author.
If the uploader is anonymous, the link isn't active.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Profile View](https://user-images.githubusercontent.com/78003700/171044734-b4daa8a4-6a5b-437e-a582-210d4fe12f6b.png)

<img width="517" alt="image" src="https://user-images.githubusercontent.com/78003700/172735545-b6ceeeef-829c-40dc-8486-07dca95503c8.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create endpoint `/api/catalog/user/:userid` that queries the DB similar to `/api/catalog`, but `where "userId" =` the provided `userid` param.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create new route in `<App>` `"user/:userid"`, which contains the element prop of `<CatalogPage>` with param `userId` = route param.
- [x] Create new route within `<Header>` for `"user"` which will show user the Home Button and set header text to `"Viewing User Vault"`
- [x] Within `<SymbolArtCard>` and `<SinglePostSymbolArt>`, `<Link>` to route `user/:userid` with Symbol Art prop provided from fetch.
- [x] Within `<CatalogPage>` check if `this.params.userId` exists, and if it does, display the name of the user above the catalog searchbar.
- [x] Adjust catalog fetch to include `'/user/:userid'` if `this.params.userid` exists
- [x] If fetch for catalog fails (i.e. unable to find user, display error similar to single post page error.

> ~~This effectively makes searching within the user possible as well without extra configuration~~ no it doesn't lmao

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
