### ISSUE TITLE
(SPLIT) Feature: User can edit/delete their Symbol Art Post metadata.

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/final-project#9]
# 🍴 **SPLITTING ISSUES** 
##### (that's supposed to be a fork)

- [ ] #38
- [ ] #39

---

# ✏️ Previous Writeup: 

## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their Symbol Art Upload details
User can delete their Symbol Art from the database

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In single post view, upon clicking edit, user is presented a prefilled form modal with post details. They can change it and confirm to update the post.
Upon clicking delete, user is presented a confirmation modal for deletion. Upon clicking delete, the post is removed from the database and they return to the previous view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/78003700/172952796-fbf3fd87-d5ae-41d6-ac71-c7962aa3785d.png">

![XS_ Single Post](https://user-images.githubusercontent.com/78003700/171045862-a0f74a9f-c51e-43c3-93f4-2bbbb0625bf2.png)

![MD_ Single Post](https://user-images.githubusercontent.com/78003700/171045870-d5187fe0-3de6-4b69-bbf2-33dafc5042f1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Create new authorized endpoint `/api/posts/edit:id` that runs auth middleware and takes a JSON object payload with edit details

```json
{
	title: string,
	name: string,
	array: string[]
}
```

- [ ] Validate `'x-access-token'` via auth middleware and set `req.user` to payload.
- [ ] Parse through data same way as done for `/api/upload/`
- [ ] Use SQL Update to update where `postId` === and `userId === req.user.id` (the `where` clause will return negative if payload userid is not equal, and there will be no rows returning)
- [ ] Validate inputs
- [ ] Create endpoint `/api/posts/delete/:id` where id is the post id and checks for `'x-access-token'` header, and removes with `sql` query similar to `/api/posts/edit...` [[sql-delete]]

```sql

delete from "posts"
where 
	"postId" = $1 and 
	"userId" = $2
returning *
;

```

- [ ] Throw 404s if posts aren't found
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Add context menu `<SymbolArtContextMenu>` positioned to right side of `<SymbolArtCard>`  title, displaying edit and delete post options. Only visible if the post's `userId` matches the current `AppContext.userId`
	- [ ] Attach the same component to `<SinglePostSingleArt>`
- [ ] Create form modal components that handle editing and deleting, using `<DaisyModal>` to handle displaying it. 
- [ ] For edit form, take prop of current Symbol Art data and prefill form state and preview image with the data.
	- [ ] Use the same form input logic as `upload.jsx`
	- [ ] Handle submit by sending a fetch request with the current `AppContext.usertoken` to `/api/posts/edit`, and close modal upon success.
- [ ] For delete form, take prop of Symbol Art data and, upon clicking confirm, delete the entry using `/api/posts/edit/:id` and send x-access-token with current user token as header.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by joseph-bravo** [comment]
Splitting this issue up
